

securex:
  nam: "https://visibility.amp.cisco.com"
  amea: "https://visibility.eu.amp.cisco.com"
  apjc: "https://visibility.apjc.amp.cisco.com"

amp:
  nam:  "https://api.amp.cisco.com/v3"
  emea: "https://api.eu.amp.cisco.com/v3"
  apjc: "https://api.apjc.amp.cisco.com/v3"